cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views
from quotes.views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home_page"),
    path("quote/", include("quotes.urls")),
    path("show_all/", views.show_all, name="show_all_quotes"),
    path("about/", views.about, name="aboutpage"),
    path("formdata/", include("formdata.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("blog/", include("blog.urls")),
    path("mini_fb/", include("mini_fb.urls")),
    path("voter_analytics/", include("voter_analytics.urls")),
    path('finalproject/', include("finalproject.urls")),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproject/urls.py
# File: urls.py
# Author: Mohammed Abaherah (abaherah@bu.edu) 14 April 2025
# Description: Has the paths to all the correct views

from django.urls import path
from .views import  ShowAllProfilesView, ShowProfilePageView, CreateProfileView, ShowMapView, ShowCouplePostsView, DeleteCouplePostView, UpdateCouplePostView
from .views import SendInvitationView, RespondToInvitationView, ShowInvitationsView, show_events, RSVPEventView, MyRSVPEventsView, save_locations, CreateCouplePostView
from django.contrib.auth import views as auth_views
from finalproject import views

'''our url patterns so we can link to the page we want to show'''
urlpatterns = [
    
    path('', ShowAllProfilesView.as_view(), name="show_all_profiles"),
    path('profile/<int:pk>/', ShowProfilePageView.as_view(), name='show_userprofile'),
    path('create_userprofile/', CreateProfileView.as_view(), name='create_userprofile'), 
    path('login/', auth_views.LoginView.as_view(template_name='finalproject/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='show_all_profiles'), name='logout'),
    path('profile/invite/send/<int:to_user_pk>/', SendInvitationView.as_view(), name='send_invitation'),
    path('invite/respond/<int:invite_id>/', RespondToInvitationView.as_view(), name='respond_invite'),
    path('invitations/', ShowInvitationsView.as_view(), name='show_invitations'),
    path('events/', show_events, name='show_events'),
    path('events/rsvp/', RSVPEventView.as_view(), name='rsvp_event'),
    path('events/my_rsvps/', MyRSVPEventsView.as_view(), name='my_rsvp_events'),
    path('map_view', ShowMapView.as_view(), name='map_view'),
    path('save_locations/', save_locations, name='save_locations'),
    path('post/create/', CreateCouplePostView.as_view(), name='create_couple_post'),
    path('couple/memories/<int:pk>/', ShowCouplePostsView.as_view(), name='show_couple_posts'),
    path('couple/post/<int:pk>/delete/', DeleteCouplePostView.as_view(), name='delete_couple_post'),
    path('couple/post/<int:pk>/update/', UpdateCouplePostView.as_view(), name='update_couple_post'),
    ]

hw/urls.py
from django.urls import path
from django.conf import settings
from . import views

urlpatterns = [ 
    path(r'', views.home, name="home"),
]

finalproject/models.py
# File: models.py
# Author: Mohammed Abaherah (abaherah@bu.edu) 14 April 2025
# Description: Contains models which model the data attributes of individual Users

from datetime import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class UserProfile(models.Model):
    '''Models the profile of one of our users on the app'''

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="finalproject_profile")
    first_name = models.CharField(max_length=100, blank=True)
    nick_name = models.CharField(max_length=100, blank=True)
    address = models.TextField(blank=True)
    email = models.EmailField(unique=True, blank=True)
    dob = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.nick_name}"

    def get_absolute_url(self):
        '''Returns the reverse URL of the profile so we can return the user to the correct URL after submitting'''
        return reverse('show_userprofile', kwargs={"pk": self.pk})

    def get_partner(self):
        '''Returns the partner of the current user, if any'''
        couple = Couple.objects.filter(models.Q(user1=self) | models.Q(user2=self)).first()
        if couple:
            return couple.user2 if couple.user1 == self else couple.user1
        return None
    
    def add_partner(self, partner):
        """Associates the current user with the given partner in a couple."""
        Couple.objects.create(user1=self, user2=partner)    

class Couple(models.Model):
    """Models the Couple of two users on the app that are connected"""
    
    user1 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user2')

    anniversary_date = models.DateField()
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user1} & {self.user2}'


class Invitation(models.Model):
    """Models the invitation system which is used to ask users to become one's partner"""

    from_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name= "from_user")
    to_user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name= "to_user")
    message = models.TextField(blank=True)
    sent_at = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"{self.from_user} invited {self.to_user}"
    


class EventRSVP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event_id = models.CharField(max_length=200)  
    event_title = models.CharField(max_length=500)
    attending = models.BooleanField(default=True)
    rsvp_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} RSVP'd to {self.event_title}"
    

class CouplePost(models.Model):
    '''Models a post made by a couple.'''
    couple = models.ForeignKey(Couple, on_delete=models.CASCADE)
    message = models.TextField(blank=True)
    time_stamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Post by {self.couple} at {self.time_stamp}'

    def get_absolute_url(self):
        return reverse('show_couple_posts', kwargs={"pk": self.couple.pk})


class CoupleImage(models.Model):
    '''Models an image belonging to a couple post.'''
    couple = models.ForeignKey(Couple, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='couple_images/', blank=True)
    caption = models.TextField(blank=True)
    time_stamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.caption}'


class CouplePostImage(models.Model):
    '''Connects an image to a couple's post.'''
    image = models.ForeignKey(CoupleImage, on_delete=models.CASCADE)
    post = models.ForeignKey(CouplePost, on_delete=models.CASCADE)

    def __str__(self):
        return f'Image {self.image} in Post {self.post}'

finalproject/views.py
# File: views.py
# Author: Mohammed Abaherah (abaherah@bu.edu) 14 April 2025
# Description: Defines our views to display what we want

from collections import defaultdict
from django.db.models import Q
from django.utils import timezone

from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import  DetailView, CreateView, View, ListView, TemplateView,DeleteView, UpdateView
from .models import UserProfile, Invitation, Couple, EventRSVP, CouplePost, CoupleImage, CouplePostImage
from .forms import CreateProfileForm, CreateCouplePostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import json
import requests
from .forms import CreateCouplePostForm
from .models import CouplePost, CoupleImage, CouplePostImage

class UserProfileMixIn:
    """Mixin to make things easier """
    def get_context_data(self, **kwargs):
        '''Add context to display the profile linked to the user and their partner'''
        context = super().get_context_data(**kwargs)
        user_profile = None
        partner = None
        couple = None
        couple_pk = None

        if self.request.user.is_authenticated:
            try:
                user_profile = UserProfile.objects.get(user=self.request.user)
                partner = user_profile.get_partner()

                if partner:
                    couple = Couple.objects.filter(
                        (Q(user1=user_profile) & Q(user2=partner)) |
                        (Q(user1=partner) & Q(user2=user_profile))
                    ).first()

                    if couple:
                        couple_pk = couple.pk

            except UserProfile.DoesNotExist:
                pass
        context["UserProfile"] = user_profile
        context["partner"] = partner
        context["couple_pk"] = couple_pk
        return context

class ShowAllProfilesView(UserProfileMixIn, ListView):
    '''Define a view class to show all Profiles'''
    
    model = UserProfile
    template_name = "finalproject/show_all_profiles.html"
    context_object_name = "profiles"

    def get_queryset(self):
        '''Returns all UserProfiles so I can display them'''
        return UserProfile.objects.all()

    def get_context_data(self, **kwargs):
        '''Overrides the getcontextdata so I can add my context to the template'''
        context = super().get_context_data(**kwargs)
        
        if self.request.user.is_authenticated:
            try:
                user_profile = UserProfile.objects.get(user=self.request.user)
                sent_invites = Invitation.objects.filter(from_user=user_profile).values_list('to_user__pk', flat=True)
                context['sent_invites'] = list(sent_invites)
            except UserProfile.DoesNotExist:
                context['sent_invites'] = []
        else:
            context['sent_invites'] = []

        return context

class ShowProfilePageView(UserProfileMixIn, DetailView):
    '''Define a view class to show a single profile page'''

    model = UserProfile 
    template_name = "finalproject/show_profile.html"
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        '''Add context to display the user's partner if they are in a couple'''
        context = super().get_context_data(**kwargs)
        partner = self.object.get_partner()  
        context['partner'] = partner
        return context

class CreateProfileView(UserProfileMixIn, CreateView):
    '''Define a view class to show the profile form'''
    
    form_class = CreateProfileForm
    template_name = "finalproject/create_profile_form.html"

    def get_context_data(self, **kwargs):
        '''Add the UserCreationForm to the context'''
        context = super().get_context_data(**kwargs)
        context['user_creation_form'] = UserCreationForm()  
        return context
    
    def get_success_url(self) -> str:
        '''Redirect to the newly created user's profile page'''
        return self.object.get_absolute_url()

    def form_valid(self, form):
        '''Handle both forms when valid'''
        user_form = UserCreationForm(self.request.POST)

        if user_form.is_valid():
            user = user_form.save()  
            profile = form.save(commit=False) 
            profile.user = user  
            profile.save()  

            return redirect('show_userprofile', pk=profile.pk)  


class SendInvitationView(UserProfileMixIn, View):
    '''A view to send a invite'''

    def post(self, request, *args, **kwargs):
        '''Sends a post Request to send an invitation'''

        try:
            from_user = request.user.finalproject_profile  
        except UserProfile.DoesNotExist:
            return HttpResponseForbidden("You need to create a profile before sending invites.")

        # check if user already has a partner
        if from_user.get_partner():
            return HttpResponseForbidden("You are already in a relationship and cannot send invitations.")

        to_user_pk = self.kwargs.get('to_user_pk')

        try:
            to_user = UserProfile.objects.get(pk=to_user_pk)
        except UserProfile.DoesNotExist:
            return HttpResponseForbidden("The user you are trying to invite does not exist.")

        if to_user.get_partner():
            return HttpResponseForbidden("This user is already in a relationship.")

        Invitation.objects.create(from_user=from_user, to_user=to_user, message="You have been invited to become a couple!")

        return redirect('show_userprofile', pk=from_user.pk)



class ShowInvitationsView(UserProfileMixIn, ListView):
    """View for users to see all their received invitations."""
    
    model = Invitation
    template_name = "finalproject/show_invitations.html"
    context_object_name = "invitations"

    def get_queryset(self):
        """Filter invitations where the logged-in user is the recipient."""
        return Invitation.objects.filter(to_user__user=self.request.user)


from datetime import datetime
from django.utils.timezone import make_aware
class RespondToInvitationView(View):
    """View to handle accepting or rejecting invitations."""

    def post(self, request, *args, **kwargs):
        invite_id = self.kwargs['invite_id']
        invitation = Invitation.objects.get(pk=invite_id)
        user_profile = request.user.finalproject_profile  

        if invitation.to_user != user_profile:
            return HttpResponseForbidden("You are not authorized to respond to this invitation.")

        response = request.POST.get('response')

        if response == 'accept':
            Couple.objects.create(user1=invitation.from_user, user2=invitation.to_user,anniversary_date=make_aware(datetime.now()).date())
            invitation.delete()

        return redirect('show_userprofile', pk=user_profile.pk)
    


class RSVPEventView(LoginRequiredMixin, View):
    """View to actually post and rsvp the event the user clicks on rsvp for"""
    @method_decorator(require_POST)
    # ^Ensures that the used method is POST
    def post(self, request, *args, **kwargs):
        '''posts the rsvp and redirects user to show events'''
        event_id = request.POST.get('event_id')
        event_title = request.POST.get('event_title')

        user = request.user
        user_profile = request.user.finalproject_profile

        # RSVPs the user
        EventRSVP.objects.get_or_create(
            user=user,
            event_id=event_id,
            defaults={'event_title': event_title}
        )

        # RSVPs the users partner automatically
        partner_profile = user_profile.get_partner()

        if partner_profile:
            EventRSVP.objects.get_or_create(
                user=partner_profile.user,  
                event_id=event_id,
                defaults={'event_title': event_title}
            )

        return redirect('show_events')




from datetime import datetime, timedelta, timezone

def show_events(request):
    """Displays events from the ticketmaster API"""
    api_key = "BrQglFQbjVOfs0K5IxUYcJfs1Odh3GAp"
    url = "https://app.ticketmaster.com/discovery/v2/events.json"

    category = request.GET.get("category", "")
    
    now_utc = datetime.now(timezone.utc)
    sixty_days_later = now_utc + timedelta(days=60)

    params = {
        "apikey": api_key,
        "countryCode": "US",
        "startDateTime": now_utc.strftime('%Y-%m-%dT%H:%M:%SZ'),
        "endDateTime": sixty_days_later.strftime('%Y-%m-%dT%H:%M:%SZ'),
        "size": 200,
        "sort": "date,asc",
    }

    if category:
        params["classificationName"] = category

    response = requests.get(url, params=params)
    data = response.json()

    raw_events = data.get("_embedded", {}).get("events", [])
    calendar_events = []
    event_counts = defaultdict(int)

    for event in raw_events:
        try:
            start_time = event["dates"]["start"].get("dateTime") or event["dates"]["start"]["localDate"]
            event_datetime = datetime.fromisoformat(start_time.replace("Z", "+00:00"))

            # Only include events in the future
            if event_datetime > now_utc:
                event_date_str = event_datetime.date().isoformat()

                if event_counts[event_date_str] < 10:
                    calendar_events.append({
                        "id": event["id"],
                        "title": event["name"],
                        "start": start_time,
                        "description": event.get("info", ""),
                    })
                    event_counts[event_date_str] += 1

finalproject/templates/finalproject/base.html
<!-- # File: base.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 14 April 2025
# Description: our base page  -->

{% load static %}

<html>
    <head>
        <title>LoveDist</title>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'styles-finalproject.css' %}">
    </head>

    <body>
        <div style="display: flex; align-items: center; justify-content: center; gap: 20px; margin: 30px 0;">
            <h1>LoveDist</h1>
            <img src="{% static 'images/milk_and_mocha.gif' %}" alt="Milk and Mocha" style="height: 80px; border-radius: 12px;">
        </div>
        
            <nav>
                <ul>
                    <li><a href="{% url 'show_all_profiles' %}">Show All</a></li>
                    {% if user.is_authenticated %}
                    {% if UserProfile %}
                        <li><a href="{% url 'show_userprofile' pk=UserProfile.pk %}">My Profile</a></li>
                        {% if not partner %}
                            <li><a href="{%url 'show_invitations' %}"> View Invites</a></li>
                        {% else %}
                        <li><a href="{% url 'map_view' %}">Our Map </a></li>
                        <li><a href="{% url 'my_rsvp_events' %}">My RSVPs</a></li>
                        <li><a href="{% url 'show_events' %}">Event Calendar</a></li>
                        {% if couple_pk %}
                            <li><a href="{% url 'show_couple_posts' couple_pk %}">Our Memories</a></li>
                        {% endif %}
                            {% endif %}
                    {% endif %}
                    <li> </li>
                    <form method="post" action="{% url 'logout' %}" class="logout-form">
                        {% csrf_token %}
                        <button type="submit" class="nav-link-button">Logout</button>
                    </form> 
                {% else %}
                    <li><a href="{% url 'create_userprofile' %}">Create Profile</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
                </ul>
            
                {% if user.is_authenticated %}
                    <div class="login-status">Logged in as: {{ user }}</div>
                {% else %}
                    <div class="login-status">Not logged in.</div>
                {% endif %}
            </nav>
            
   
           {% block content %}
           {% endblock %}
       </body>
</html>

finalproject/templates/finalproject/create_couple_post_form.html
<!-- # File: create_couple_post_form.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 28 April 2025
# Description: Couples posting cute photos and captiosn!!!!! -->

{% extends 'finalproject/base.html' %}
{% block content %}

<h1>Create a Cute Post</h1>

<form action="{% url 'create_couple_post' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <h3>Upload Cute Pictures!</h3>
    <input type="file" name="files" multiple />

    <input type="submit" value="Post!">
</form>

{% endblock %}

finalproject/templates/finalproject/create_profile_form.html
<!-- # File: create_profile_form.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 15 April 2025
# Description: Create page for user registration and profile creation -->

{% extends 'finalproject/base.html' %}

{% block content %}
<h1>Create a New Profile</h1>

<!-- display the HTML form -->
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

    <!-- User Creation Form (username, password, password confirmation) -->
    <h2>Register</h2>
    <table>
        {{ user_creation_form.as_table }}
    </table>

    <!-- Profile Creation Form (first name, last name, image, etc.) -->
    <h2>Create Profile</h2>
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

finalproject/templates/finalproject/delete_couple_post_form.html
<!-- # File: delete_couple_post_form.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 28 April 2025
# Description: delete page for status form -->

{% extends 'finalproject/base.html' %}

{% block content %}

<h1>Delete Memory</h1>

<h3>Are you sure you want to delete this memory?</h3>

{{ couplepost.message }}

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

<form action="{% url 'show_couple_posts' couplepost.couple.pk %}" method="GET">
    {% csrf_token %}
    <input type="submit" value="Cancel">
</form>

{% endblock %}

finalproject/templates/finalproject/invitation.html
<!-- # File: invitation.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 24 April 2025
# Description: Invitation Page for a user to see if they have been invited by their partner invited them to become a couple -->

{% extends 'finalproject/base.html' %}

{% block content %}

finalproject/templates/finalproject/login.html
<!-- # File: login.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 17 April 2025
# Description: Displays login -->

<!-- templates/finalproject/templates/login.html -->
{% extends 'finalproject/base.html' %}

{% block content %}

<h1>Login</h1>
<form method="post" class = "forms" action="{% url 'login' %}" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Login">

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'show_all_profiles' %}">
    {% endif %}
</form>


<hr>
Haven't started your adventure? <a href="{% url 'create_userprofile' %}">Register here</a>.
{% endblock %}

finalproject/templates/finalproject/my_rsvp_events.html
<!-- # File: my_rsvp_events.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 26 April 2025
# Description: This page is for users to see the events they rsvped to -->


{% extends "finalproject/base.html" %}
{% block content %}

<h1>My RSVP'd Events </h1>

<ul>
    {% for rsvp in rsvp_events %}
        <li>
            <strong>{{ rsvp.event_title }}</strong> (RSVP'd on {{ rsvp.rsvp_date|date:"M d, Y" }})
        </li>
    {% empty %}
        <li>You haven't RSVP'd to any events yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'show_events' %}">Back to Events Calendar</a>

{% endblock %}

finalproject/templates/finalproject/send_invitation.html
<!-- # File: send_invitation.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 24 April 2025
# Description: send invitation page -->


{% extends 'finalproject/base.html' %}

{% block content %}
<h1>Send an Invitation</h1>
<h2>Invite {{ to_user.first_name }} {{ to_user.nick_name }} to become your partner</h2>

<form method="POST" action="{% url 'send_invitation' to_user_pk=to_user.pk %}">
    {% csrf_token %}
    <p>Message:</p>
    <textarea name="message" rows="4" cols="50" placeholder="Write your invitation message..."></textarea><br>
    <button type="submit">Send Invitation</button>
</form>
{% endblock %}

finalproject/templates/finalproject/show_all_profiles.html
<!-- # File: show_all_profiles.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 17 April 2025
# Description: display page for all profiles -->

{% extends 'finalproject/base.html' %}

{% block content %}
<h1>All Beautiful People</h1>

<main class="grid-container">
    
    {% for profile in profiles %}
        <div class="profile-card">
            <a href="{% url 'show_userprofile' profile.pk %}">
                
                <img src="{{ profile.image.url }}" alt="Profile image of {{ profile.nick_name }}">
            </a>
            <h2>
                <a href="{% url 'show_userprofile' profile.pk %}">{{ profile.first_name }} {{ profile.nick_name }}</a>
            </h2>
            <h3>{{ profile.email }}</h3>

            {% if profile.get_partner %}
            <p class="relationship-badge">💞 In a relationship</p>
        {% elif profile.pk in sent_invites %}
            <p class="relationship-badge">📨 Invite already sent!</p>
        {% else %}
            <form method="POST" action="{% url 'send_invitation' to_user_pk=profile.pk %}" class="logout-form">
                {% csrf_token %}
                <button type="submit" class="invite-button">Send Invitation</button>
            </form>
        {% endif %}
            </div>
    {% endfor %}
</main>
{% endblock %}

finalproject/templates/finalproject/show_couple_posts.html
<!-- # File: show_couple_posts.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 28 April 2025
# Description: display page for all posts by the couple!!! -->


{% extends 'finalproject/base.html' %}
{% block content %}

<h1 class="memories-title">Our Memories Together</h1>

<div class="create-memory-button">
    <a href="{% url 'create_couple_post' %}">Create New Memory</a>
</div>

{% if posts %}
    <div class="memories-feed">
        {% for post in posts %}
            <div class="memory-post">
                {% for image in post.couplepostimage_set.all %}
                    <div class="memory-image-block">
                        <img src="{{ image.image.image.url }}" alt="Memory Image" class="memory-image">
                    </div>
                {% endfor %}
                <p class="memory-caption">{{ post.message }}</p>
                <p class="memory-date">{{ post.time_stamp|date:"F j, Y" }}</p>

                <div class="memory-actions">
                    <a href="{% url 'update_couple_post' post.pk %}" class="memory-action">Edit</a>
                    |
                    <a href="{% url 'delete_couple_post' post.pk %}" class="memory-action">Delete</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p style="text-align: center; margin-top: 20px;">You have no memories yet. <a href="{% url 'create_couple_post' %}">Start one now!</a></p>
{% endif %}

{% endblock %}

finalproject/templates/finalproject/show_invitations.html
<!-- # File: Show_invitations.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 24 April 2025
# Description: shows all invitations -->

{% extends 'finalproject/base.html' %}

{% block content %}
    <h2>Your Invitations</h2>

    {% if invitations %}
        <ul>
            {% for invitation in invitations %}
                <li>
                    <p><strong>{{ invitation.from_user.nick_name }}</strong> has invited you to become a couple.</p>
                    <p>Message: {{ invitation.message }}</p>
                    
                    <form method="post" action="{% url 'respond_invite' invite_id=invitation.pk %}">
                        {% csrf_token %}
                        <button type="submit" name="response" value="accept">Accept</button>
                        <button type="submit" name="response" value="reject">Reject</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have no new invitations.</p>
    {% endif %}
{% endblock %}

finalproject/templates/finalproject/show_profile.html
<!-- # File: show_profile.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 14 April 2025
# Description: display page for a single profile -->

{% extends 'finalproject/base.html' %}

{% block content %}

<main class="profile-container">

    <table class="profile-table">
        <tr>
            <td class="profile-image_solo">
                {% if profile.image and profile.image.name %}
                <img src="{{ profile.image.url }}" alt="Profile image of {{ profile.first_name }}">
            {% else %}
                <img src="{{ MEDIA_URL }}profile_images/default_profile.png" alt="Default profile image">
            {% endif %}
            </td>

            <td class="profile-info">
                <h1 class="profile-title">{{ profile.first_name }} {{ profile.nick_name}}</h1>
                <h2 class="profile-address">lives at {{ profile.address }}</h2>
                <h2 class="profile-dob">born on {{ profile.dob }}</h2>
                <h2 class="profile-email"> {{ profile.email }}</h2>

            </td>
        </tr>

        {% if partner %}
        <h2 class="profile-partner">In a relationship with {{ partner }}</h2>
    {% else %}
        <h2 class="profile-info">
            <p>Currently single.</p>
            <p>You can send an invitation to someone by hovering over their profile!</p>
        </h2>
    {% endif %}

</main>


{% endblock %}

finalproject/templates/finalproject/update_couple_post_form.html
<!-- # File: update_couple_post_form.html
# Author: Mohammed Abaherah (abaherah@bu.edu) 28 April 2025
# Description: update page for status form -->

{% extends 'finalproject/base.html' %}

{% block content %}
<div class="center">
<h1>Update Memory</h1>

<h3>Make a change to your memory caption or image!</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <label for="new_image">Upload New Image:</label>
    <input type="file" name="new_image" id="new_image"><br><br>

    <input type="submit" value="Update">
</form>

<form action="{% url 'show_couple_posts' couplepost.couple.pk %}" method="GET">
    {% csrf_token %}
    <input type="submit" value="Cancel">
</form>
</div>
{% endblock %}